---
title: "R Notebook"
output: html_notebook
---

```{r}
library(foreign)
library(haven)
library(dplyr)
library(ggplot2)
library(fmtr)
#library(reshape2)
library(tidyr)
data_directory_region_number <- "./datasets/datasets_variable_e - region_number.csv"
data_directory_2019_hl_normal <- "../cleaned_df_exports/df_2019_hl_normal.sav"
data_directory_2014_hl_normal <- "../cleaned_df_exports/df_2014_hl_normal.sav"
data_directory_2006_hl_normal <- "../cleaned_df_exports/df_2006_hl_normal.sav"
data_directory_2000_hl_normal <- "../cleaned_df_exports/df_2000_hl_normal.sav"
region_number_e_raw <- read.csv(data_directory_region_number)
df_2019_normal_raw <- read_spss(data_directory_2019_hl_normal)
df_2014_normal_raw <- read_spss(data_directory_2014_hl_normal)
df_2006_normal_raw <- read_spss(data_directory_2006_hl_normal)
df_2000_normal_raw <- read_spss(data_directory_2000_hl_normal)
```

```{r}
region_number_e_tibble <- as_tibble(region_number_e_raw)
#region_number_e_tibble$region_number <- as.factor(region_number_e_tibble$region_number)
#summary(region_number_e_tibble)
#region_number_e_tibble$region_number <- as.factor(region_number_e_tibble$region_number)
#df <- melt(region_number_e_tibble, id.vars = c("e_2019", "e_2014", "e_2006", "e_2000"))
df <- region_number_e_tibble %>% pivot_longer(cols=c("e_2019", "e_2014", "e_2006", "e_2000"), names_to = "year", values_to="e_value")

str(df)
gg_geo_e <- ggplot(df, aes(x=region_number, y=e_value)) + geom_line(aes(color=year)) + geom_point() + scale_x_continuous(breaks = seq(1, 10, by = 1)) + geom_hline(aes(yintercept=1, colour="baseline=1"))+
  labs(y=expression("Odds to Region 10 ("*e**beta*")"), x="Region Number")

#str(gg_geo_e

ggsave(path="gg_plots", filename="gg_geo_e.png", plot=gg_geo_e, width=20, height = 12, units = "cm")
ggsave(path="../../../write-up/graphics", filename="gg_geo_e.png", plot=gg_geo_e, width=20, height = 12, units = "cm")

```



